graph:
  processed_graphs: /data1/GraphModellingExperiments/AssemblyDemo/GraphConstruction
  window: 30
  overlap: 15
  selected_class:
    - 1
    - 2
    - 6
  type: "WithHands"

training:
  split_props:
    - 15
    - 30
    - 50
  batch_size: 256
  output: /data1/GraphModellingExperiments/AssemblyDemo/TrainEval
